### ISSUE TITLE
Player can walk past un-hacked barrier for objective "python_basics_numbers_math" 

### ISSUE THREAD

**Issue by rmkubik** [TwilioQuest/twilioquest-python#7]
This issue was reported in Discord by user TheRealrA9:

https://discord.com/channels/570292611215130634/900321423422271529/985007660015448125

https://user-images.githubusercontent.com/9389625/173169541-71840840-7dcb-4e45-8a38-3615497e8f5f.mp4

**Comment by MarvelProgramming** [comment]
As I was working on a fix for this, I found a couple other areas to touch up. Should all be corrected in #8

https://user-images.githubusercontent.com/51891409/176978987-86f99d42-533a-48ce-a2d9-e47cf5ee65b7.mov




https://user-images.githubusercontent.com/51891409/176980645-df98a215-96d8-4690-92bd-3794e0c6a6cf.mov

**Comment by MarvelProgramming** [comment]
This was fixed in #8
